// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCohML7S0HlipdugmKa9mMsNb0JG5AdFrU',
    appId: '1:654473554359:android:dc74d3d040ba7a7f496032',
    messagingSenderId: '654473554359',
    projectId: 'supercycle-representative',
    storageBucket: 'supercycle-representative.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHcLTnugiDjePiEYui4-cJQ41CqHkeTfw',
    appId: '1:654473554359:ios:cdd2e0cf0143766b496032',
    messagingSenderId: '654473554359',
    projectId: 'supercycle-representative',
    storageBucket: 'supercycle-representative.firebasestorage.app',
    androidClientId: '654473554359-3fabl8kq1gcc4md43mt4u0acn9polrbi.apps.googleusercontent.com',
    iosClientId: '654473554359-otdn0n5dp0lrllnbaj5qc99shdn2shog.apps.googleusercontent.com',
    iosBundleId: 'com.supercycle.representative',
  );

}